---
- name: Redis data container
  docker:
    name: data/redis
    image: busybox
    state: present
    volumes:
      - /data


- name: Redis container
  docker:
    image: redis
    name: redis
    state: running
    volumes_from: data/redis
    command: redis-server --appendonly yes


- name: Node container
  docker:
    name: node
    image: node:0.12.4
    state: reloaded
    pull: always
    links:
    - "redis:redisbootstrap"
    ports:
    - "8080:9000"
